### ISSUE TITLE
RFC: Major API Changes

### ISSUE THREAD

**Issue by mikolasstuchlik** [futuredapp/FTAPIKit#29]
#18 #15 #24 

This issue is meant to accompany future Pull Requests that will be associated with topic discussed in this issue. This issue will describe my personal opinions about the FTAPIKit and its future and I will design my future additions into the FTAPIKit with accordance to this issue. 

Suggestions in this issue do not presume 100% interface compatibility with old instances.

Please feel free to comment and share your opinions about changes suggested in this document.

**What should FTAPIKit be**

FTAPIKit should have following core features:
- Define declarative approach for managing endpoints (define what does an endpoint looks like and what features are supported - http methods, content type etc.)
- Declare joint method for executing endpoints
- Avoid restricting programmer in implementing any feature described in HTTP standard
- Avoid using any concrete types
- Avoid declaring functionality outside of HTTP standard (for example custom authentication)
- FTAPIKit should provide it's own easy-to-use easy-to-deploy reference implementation for Apple platforms

FTAPIKit should have following optional features implemented in default implementation:
- Default implementation must support URLSession
- Default implementation should support other networking services and encoders without too much struggle
- Default implementation must support JSON encoding/decoding
- Default implementation must support extendibility without overriding by manipulating request object after translation from declared endpoint before executing, result object after process was finished before finish callbacks are executed and task object while task is being processed
- Default implementation should have good support for async frameworks like PromiseKit and RxSwift

**What FTAPIKit currently is**

FTAPIKit has good support for following core features
- Define declarative approach for managing endpoints (define what does an endpoint looks like and what features are supported - http methods, content type etc.)
- Declare joint method for executing endpoints
- Avoid using any concrete types
- FTAPIKit should provide it's own easy-to-use easy-to-deploy reference implementation for Apple platforms

FTAPIKit has poor or no support for following core features: 
- Avoid restricting programmer in implementing any feature described in HTTP standard (multipart upload/download, endpoint extendibility)
- Avoid declaring functionality outside of HTTP standard (for example custom authentication)

FTAPIKit has good following optional features implemented in default implementation:
- Default implementation must support URLSession
- Default implementation must support JSON encoding/decoding
- Default implementation should have good support for async frameworks like PromiseKit and RxSwift

FTAPIKit has bad or no following optional features implemented in default implementation:
- Default implementation should support other networking services and encoders without too much struggle
- Default implementation must support extendibility without overriding by manipulating request object after translation from declared endpoint before executing, result object after process was finished before finish callbacks are executed and task object while task is being processed

**What I see as the main problems of FTAPIKit now**

- Default implementation restricts user to use only JSON encoder/decoder
- Default implementation has multiple access interfaces that do the same (interface for pre-processing (signing) - by delegate, interface for post-processing - custom error initializer, interface for task managing - closure)
- Default implementation does not support extending of default protocols (callbacks return endpoint as concrete type)
- Core types and default implementation should be more clearly separated
- It will be somewhat difficult to implement download stream under current conditions

**My suggestions, development orientation and points of interest**
- _Default implementation restricts user to use only JSON encoder/decoder_ Default implementation should provide capsule for decoders and encoders. This also applies for networking service since some services provide the same features by different means (completion blocks, delegates, references,...)
- _Default implementation has multiple access interfaces that do the same (interface for pre-processing (signing) - by delegate, interface for post-processing - custom error initializer, interface for task managing - closure)_ Provide all blocking and unblocking callbacks as closures.
- _Default implementation does not support extending of default protocols (callbacks return endpoint as concrete type)_ By getting rid of callbacks disassociated from the main caller function, callbacks provided in the main caller function will know the concrete type of APIEndpoint conforming type.
- _Core types and default implementation should be more clearly separated_ Use podspec or different directory.
- _It will be somewhat difficult to implement download stream under current conditions_ Using previously described additions, APIResponse protocol could be extended to include custom flag (of any sort), that output should be stream and by subclassing of default implementation (some frameworks like URLSession only provide output streams by delegate) and completion trigger should be released before the process is finished

**Comment by mkj-is** [comment]
We have discussed many of these issues and APIKit is currently rewritten to reflect those requirements and ideas. Mainly:

- Default implementation restricts user to use only JSON encoder/decoder
- Core types and default implementation should be more clearly separated
- It will be somewhat difficult to implement download stream under current conditions
- Default implementation has multiple access interfaces that do the same (interface for pre-processing (signing) - by delegate, interface for post-processing - custom error initializer, interface for task managing - closure)
- Default implementation must support extendibility without overriding by manipulating request object after translation from declared endpoint before executing, result object after process was finished before finish callbacks are executed and task object while task is being processed
- Default implementation should support other networking services and encoders without too much struggle
- Avoid restricting programmer in implementing any feature described in HTTP standard (multipart upload/download, endpoint extendibility)

Hopfully all the items mentioned here should be improved by #47.
